---
# vars file for ssl-configuration
certification_directory: "/etc/ssl"
private_key_path: "{{certification_directory}}/private/private.key"
csr_path: "~/client.csr"
signed_crt: "{{certification_directory}}/certs/self-signed.crt"
ip_address: "18.222.65.52"
